# Generated by Django 5.2.7 on 2025-10-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
